theme: jekyll-theme-cayman

# Setup
title:        LENCE
tagline:      A not for profit software development organization
baseurl:      ""
paginate:     1

---
layout: default
title: {{ site.name }}
---